### PR TITLE
multiple locations (untested)

### PR DESCRIPTION
**Pull request by cfoour**
Ignore the unnecessary changes about the naming and the removal of some vehicles, it was made to match my server

### CODE REVIEW

**Comment by xViperAG** [comment]
Just looking to see about it. Gonna be working on it in the meantime.

**Comment by cfoour** [comment]
i closed it to make a proper PR as this one includes some chnages i did for my server

**Comment by cfoour** [comment]
> Just looking to see about it. Gonna be working on it in the meantime.


i closed it to make a proper PR as this one includes some changes i did for my server

**Comment by xViperAG** [comment]
Aight I'll reclose then.

**Pull request closed without merging**
